import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Nav from '../components/Nav';

export default function Home() {
    return (
        <>
            <Head>
                <title>test app</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Nav />
                <div className={styles.header}>
                <div className={styles.head}>
                    <div className={styles.text}>
                        <h1>E-commerce market</h1>
                        <p>Selling online has become a popular way for businesses to reach a wider audience and increase their sales. With the rise of e-commerce platforms, businesses can easily set up an online store and sell their products or</p>
                        <input type="button" value="Learn more" /> <a href='#w'>Start selling</a>
                    </div>
                    <img src="http://127.0.0.1:5500/assets/0.png" alt="" />
                </div>
                <div className={styles.foot}>
                    <section>
                        <div className={styles.text}>
                            <h2 className={styles.mainTitle}>Cheap&Luxury <span>furnishings</span></h2>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In undemolestias dolores perferendis laborum quia!</p>
                            <a to="#w">Learn more</a>
                        </div>
                        <img src="http://127.0.0.1:5500/assets/11.png" alt="" />
                    </section>
                    <section>
                        <img src="http://127.0.0.1:5500/assets/10.png" alt="" />
                        <div className={styles.text}>
                            <h2 className={styles.mainTitle}>Start selling your old <span>Things</span></h2>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In undemolestias dolores perferendis laborum quia!</p>
                            <a to="#w">Learn more</a>
                        </div>
                    </section>
                </div>
            </div>
            </main>
        </>
    )
}
